### PR TITLE
Added centihavoc for stack shenanigans

### PR DESCRIPTION
**Pull request by andrewbuss**
It's a somewhat larger havoc that tries to detect stack corruptions. It keeps a buffer at the bottom of the stack and a checksum of that buffer at the top of that stack. Periodically it verifies the checksum and randomizes the buffer. If stacks are not separated properly, this will trample over the stack of another thread.

### CODE REVIEW

**Comment by metakirby5** [comment]
People are going to be pretty salty if this case causes new failures :wink:

**Comment by metakirby5** [comment]
This is weird, it appears to be passing on your tester but not on mine:
Test Results

**Comment by andrewbuss** [comment]
Stack stuff is really nondeterministic. Does that always happen when you
run both testers a few times?

**Comment by andrewbuss** [comment]
Also, centihavoc allocates space for 15000 integers, leaving 2768 bytes of extra stack space. If you think you might be having problems with overflow (from threading library functions or printf), you might adjust that. The reference library consistently passed centihavoc. 

If you can put a bound on the stack depth of library function calls, you can allocate that much extra space when you set up your setjmp environment, so that even if a thread uses exactly 64K of stack space, it doesn't trample adjacent threads. I'm not sure how strictly the autograder will test this though.

**Pull request merged**
